# Generated by Django 4.2.4 on 2023-08-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_registrations', to='Main.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_registrations', related_query_name='user_registration_permission', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
