# Generated by Django 4.2.3 on 2023-08-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_creategroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('contact', models.PositiveIntegerField()),
                ('email', models.EmailField(default=True, max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.AddField(
            model_name='contribution',
            name='member_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
