# Generated by Django 4.2.4 on 2023-08-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_customuser_userregistration_remove_contribution_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_repaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.loan')),
            ],
        ),
    ]
