# Generated by Django 4.2.4 on 2023-08-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_loan_is_repaid_loan_remaining_amount_loanrepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loanfunding',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='loanfunding',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='loan',
        ),
        migrations.AddField(
            model_name='contribution',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='loanfunding',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='loanfunding',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
