# Generated by Django 4.2.3 on 2023-08-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_usergroupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.creategroup'),
        ),
    ]
