# Generated by Django 4.2.3 on 2023-08-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_loan_is_repaid_loan_remaining_amount_loanrepayment'),
        ('Main', '0007_alter_usergroupmembership_group'),
    ]

    operations = [
    ]
